CREATE TABLE if not exists prices(
ID INT NOT NULL AUTO_INCREMENT,
BRAND_ID INT not null,
START_DATE DATETIME not null,
END_DATE DATETIME not null,
PRICE_LIST VARCHAR(10),
PRODUCT_ID VARCHAR(10),
PRIORITY INT not null,
PRICE DECIMAL (10,2),
CURR VARCHAR(3));